#!/bin/sh
set -e

cd ~/.vtime

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vtime/my_configs.vim

set runtimepath+=~/.vtime
set packpath+=~/.vtime

source ~/.vtime/vimrcs/basic.vim
source ~/.vtime/vimrcs/filetypes.vim
source ~/.vtime/vimrcs/plugins_config.vim
source ~/.vtime/vimrcs/extended.vim
try
  source ~/.vtime/my_configs.vim
catch
endtry' > ~/.vimrc

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
